ENT.Type = "anim"
ENT.Base = "ss_powerup_base"
ENT.PrintName = "Serious Speed"
ENT.Category = "Quake Powerups"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true